/** @format */

import React from 'react';
export const Dates = [
  {
    date: '17/09/2022',
  },
];

export const Markets = [
  {
    id: 1,
    name: 'SOUTH DELHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: true,
    isActive: true,
  },
  {
    id: 2,
    name: 'LUCKY 7',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: true,
    isActive: true,
  },
  {
    id: 3,
    name: 'SATTA KING',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 4,
    name: 'GHAZIYABAD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: true,
    isActive: true,
  },
  {
    id: 5,
    name: 'CHARMINAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 6,
    name: 'DISAWER',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 7,
    name: 'GALI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 8,
    name: 'FARIDABAD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 9,
    name: 'GAZIYABAD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 10,
    name: 'SOUTH DELHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 11,
    name: 'PUNE',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 12,
    name: 'RANCHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 13,
    name: 'DELHI GOLD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 14,
    name: 'HINDU STAN',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 15,
    name: 'KAVERI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 16,
    name: 'OLD DELHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 17,
    name: 'KASHIPUR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 18,
    name: 'MOHALLA',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 19,
    name: 'PUNJAB',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 20,
    name: 'PUNE GOLD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 21,
    name: 'SUPER DELHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 22,
    name: 'DUBAI MARKET',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 23,
    name: 'PATNA CITY',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 24,
    name: 'PARAS',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 25,
    name: 'DELHI STATE',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 26,
    name: 'TAJ',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 27,
    name: 'UTTAR PRADESH',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 28,
    name: 'FARIDABAD GOLD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 29,
    name: 'PESHA WAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 30,
    name: 'SHALIMAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 31,
    name: 'WAZIR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 32,
    name: 'BIKANER SUPER',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 33,
    name: 'MUMBAI BAZAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 34,
    name: 'LUCKNOW GOLD',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 35,
    name: 'SAI RAM',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 36,
    name: 'HARIDWAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 37,
    name: 'MIRZAPUR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 38,
    name: 'TAJ BAZAR',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 39,
    name: 'DABANG DELHI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
  {
    id: 40,
    name: 'LAXMI',
    time: '123',
    oldResult: '00',
    newResult: '00',
    isPremium: false,
    isActive: true,
  },
];

export const Contents = [
  {
    id: 1,
    isContent: true,
    lineA: '👑 लीक - लीक - लीक 👑',

    lineB:
      'जल्दी MSG करके गेम बुक करवाये सिंगल जोड़ी में GUARANTEE KE SATH KAM HOGA AAPKA✅',
    line1:
      'गली दिशावर में कंपनी से लीक जोड़ी जो कटेगी नही हम आपको देंगे।जल्दी से हमारे पास आएं और लीक नंबर लेके जाएं और लाखो कमाएं।दो दिन में नुकसान पूरा कराने की गारंटी हमारी।जो लोग मोटे कर्जे में है और मोटा खेलते है वो सबसे पहले संपर्क करें अभी।जो लोग लॉस में है बिल्कुल देर न करें।अभी हमें कॉल करें या फिर व्हाट्सएप पे मैसेज करें ।आज से ही कमाई चालू करें',
    line2:
      '👑 सिंगल जोड़ी मै होगा धमाका 💣 गली-दिसावर-फरीदाबाद- गाजियाबाद चारों गेम में सिंगल जोड़ी में गेम पास होगी 101% गैरंटी के साथ👍 गेम किसी का बाप भी नहीं काट सकता गेम काटने वाले को इनाम💵',
    line3:
      ' 👉 फ़रीदाबाद 👉ग़ाज़ियाबाद 👉गली 👉दिसावर 100% PASS👈 ✅ 🤝 जो कहते है करके दिखाते है 👍✅ 👉 अभी गेम लेने के लिए WhatsApp करे 👍',
    name: 'NAME (Company CEO & MD) ✅',
    contact: '☎️PHONE NUMBER☎️',
  },
  {
    id: 2,
    isContent: true,
    lineA: '👑KING OF SATTA👑',
    lineB:
      'जल्दी MSG करके गेम बुक करवाये सिंगल जोड़ी में GUARANTEE KE SATH KAM HOGA AAPKA✅',

    line1:
      '👑 सिंगल जोड़ी मै होगा धमाका 💣 गली-दिसावर-फरीदाबाद- गाजियाबाद चारों गेम में सिंगल जोड़ी में गेम पास होगी 101% गैरंटी के साथ👍 गेम किसी का बाप भी नहीं काट सकता गेम काटने वाले को इनाम💵',
    line3:
      ' 👉 फ़रीदाबाद 👉ग़ाज़ियाबाद 👉गली 👉दिसावर 100% PASS👈 ✅ 🤝 जो कहते है करके दिखाते है 👍✅ 👉 अभी गेम लेने के लिए WhatsApp करे 👍',
    name: 'NAME  ✅',
    contact: '☎️PHONE NUMBER☎️',
  },
  {
    id: 3,
    isContent: true,
    lineA: '👑 लीक - लीक - लीक 👑',
    lineC:
      'जल्दी MSG करके गेम बुक करवाये सिंगल जोड़ी में GUARANTEE KE SATH KAM HOGA AAPKA✅',
    line1:
      'गली दिशावर में कंपनी से लीक जोड़ी जो कटेगी नही हम आपको देंगे।जल्दी से हमारे पास आएं और लीक नंबर लेके जाएं और लाखो कमाएं।दो दिन में नुकसान पूरा कराने की गारंटी हमारी।जो लोग मोटे कर्जे में है और मोटा खेलते है वो सबसे पहले संपर्क करें अभी।जो लोग लॉस में है बिल्कुल देर न करें।अभी हमें कॉल करें या फिर व्हाट्सएप पे मैसेज करें ।आज से ही कमाई चालू करें',
    line2:
      '👑 सिंगल जोड़ी मै होगा धमाका 💣 गली-दिसावर-फरीदाबाद- गाजियाबाद चारों गेम में सिंगल जोड़ी में गेम पास होगी 101% गैरंटी के साथ👍 गेम किसी का बाप भी नहीं काट सकता गेम काटने वाले को इनाम💵',
    line3:
      ' 👉 फ़रीदाबाद 👉ग़ाज़ियाबाद 👉गली 👉दिसावर 100% PASS👈 ✅ 🤝 जो कहते है करके दिखाते है 👍✅ 👉 अभी गेम लेने के लिए WhatsApp करे 👍',
    name: 'NAME ✅',
    contact: '☎️PHONE NUMBER☎️',
  },
  {
    contentkey: 'SATTA MATKA KING MATKA RESULT',
    isKey: true,
    contentkeyword:
      'Satta king chart, Satta king, live Gali satta, Deshawar live result, Gali live result, Satta matka, Satta matka king, Satta king up, Satta king 2020 chart, Satta king desawar, Satta king gali, Gali live result, Disawar live result, Satta Number, Satta Game, Gali Number, Delhi Satta king, Satta Bazar, Black satta king, Gali Single Jodi, Black Satta Result, Desawar Single Jodi',
  },
  {
    contentHead: 'What is Satta king ?',
    isActive: true,
    contentPara:
      "'Satta King(सट्टा किंग) is a kind of lottery game based on numbers from 00 to 99 which comes under Gambling. The real name of this game is Satta Matka, in which Satta means betting or gambling and Matka means a pot through which a number is drawn out. In the Satta Matka game, people wager money on their chosen numbers from between 00 to 99. After which, a number is drawn out of the pot. Whichever person's number was drawn out, he would win the prize and people called him as the Sattaking. Satta King(सट्टा किंग) is not the name of the game, it was the title used to honor the winner of the Satta Matka. But as this game became popular, people started knowing it by the name of Sattaking.",
  },
  {
    contentHead: 'History of Satta Matka game',
    isActive: true,
    contentPara:
      "If you too are interested in knowing about the history of Satta Matka, then you have come to the right place. Satta Matka Satta king result started in the 1950s, while most people bet on the opening and closing prices of cotton, which was then sent from Bombay Cotton Exchange to New York Cotton Exchange, via teleprinters. 1. In 1961, when the New York Cotton Exchange banned this type of betting, then these punters / gamblers had to think of other ways to keep this satta matka Satta King Result business alive. 2. In 1962, a second emperor, Kalyanji Bhagat, who owned a grocery shop from Worli, started Kalyan Worli Matka in which, according to his new rules, even the poorest of the poor could stake it. 1 rupees only. 3. At the same time after two years, Ratan Khatri resumed the New Worli Matka in 1964, in which he made some changes in the rules of the game. 4. Where Kalyanji Bhagat’s Matka used to run all days of the week, Ratan Khatri’s Matka used to run only six days a week. 5. When textile mills became more popular in Mumbai, most of the mill workers started playing matka more, due to which more bookies started opening their shops around these mill areas and thus Central Mumbai is a lot Matka business has become a big hub in Mumbai. 6. There was a time when the matka business reached its peak between the 1980s and 1990s, at that time there was a business of about Rs 500 crore per month. 7. After repeated raid of Mumbai Police, there was a lot of damage at the bases of satta matka. So bookies was forced to take these bases out of the city. At the same time, some had to be taken to other states also like Gujarat, Rajasthan etc. 8. When there are no more options of betting or satta left, then bookies have started to concentrate on other gambling such as online lotteries. At the same time, Some gamblers started playing betting on cricket matches. Just as the interference of the police started increasing, this business also started to suffer a lot. At the same time when Kalyanji Bhagat's son Suresh Bhagat was killed, then in 2008, the satta was almost closed. Even after this, other Satta Matka are more popular today such as Gali , Disawar, Faridabad, Delhi Bazaar, Kuber, JD Durga, New Faridabad, etc.). Next you will get complete information related to Satta Matka in this article.",
  },
  {
    contentHead: 'How many types of Satta king game ?',
    isActive: true,
    contentPara:
      'The Satta King game dont have any type itself. When people start a new game in Sattaking, people name the game with the name of different City, State and places. Such as Gali, Deshawar, Ghaziabad, Faridabad, Mumbai Morning, Delhi King, Dubai King etc. Although there are many types of Satta King games played in India, but out of all, 4 games (Gali, Deshawar, Gaziyabad, Faridabad) are played the most in the whole of India. Deshawar game is most popular. This game is from Dubai and is operated from  ',
  },
  {
    contentHead: 'History of Satta Matka game',
    isActive: true,
    contentPara:
      "If you too are interested in knowing about the history of Satta Matka, then you have come to the right place. Satta Matka Satta king result started in the 1950s, while most people bet on the opening and closing prices of cotton, which was then sent from Bombay Cotton Exchange to New York Cotton Exchange, via teleprinters. 1. In 1961, when the New York Cotton Exchange banned this type of betting, then these punters / gamblers had to think of other ways to keep this satta matka Satta King Result business alive. 2. In 1962, a second emperor, Kalyanji Bhagat, who owned a grocery shop from Worli, started Kalyan Worli Matka in which, according to his new rules, even the poorest of the poor could stake it. 1 rupees only. 3. At the same time after two years, Ratan Khatri resumed the New Worli Matka in 1964, in which he made some changes in the rules of the game. 4. Where Kalyanji Bhagats Matka used to run all days of the week, Ratan Khatris Matka used to run only six days a week. 5. When textile mills became more popular in Mumbai, most of the mill workers started playing matka more, due to which more bookies started opening their shops around these mill areas and thus Central Mumbai is a lot Matka business has become a big hub in Mumbai. 6. There was a time when the matka business reached its peak between the 1980s and 1990s, at that time there was a business of about Rs 500 crore per month. 7. After repeated raid of Mumbai Police, there was a lot of damage at the bases of satta matka. So bookies was forced to take these bases out of the city. At the same time, some had to be taken to other states also like Gujarat, Rajasthan etc. 8. When there are no more options of betting or satta left, then bookies have started to concentrate on other gambling such as online lotteries. At the same time, Some gamblers started playing betting on cricket matches. Just as the interference of the police started increasing, this business also started to suffer a lot. At the same time when Kalyanji Bhagat's son Suresh Bhagat was killed, then in 2008, the satta was almost closed. Even after this, other Satta Matka are more popular today such as Gali , Disawar, Faridabad, Delhi Bazaar, Kuber, JD Durga, New Faridabad, etc.). Next you will get complete information related to Satta Matka in this article.",
  },
  {
    contentHead: 'How to play satta king game ?',
    isActive: true,
    contentPara:
      'In Satta King game, people wager bets on their chosen numbers between 0 and 99. For this the bettors contact their area’s Khaiwal. Khaiwal works as a mediator/middle man between the bettors and the game operators. Every Khaiwal collects money and the number from the players of his area and sends it to the company. And once a winner is declared he collects the winnings from the company and delivers it to the winning bettor. At a predefined time the Sattaking company opens a random number. The winning bettor receives 90 times the money he wagered.',
  },
  {
    contentHead: 'How much profit you can earn from satta king ?',
    isActive: true,
    contentPara:
      'Suppose if someone has bet 10 rupees on a number, then if that number is opened then the user will get 10 x 90 = 900 Rupees. Similarly, users will get 1800 rupees for 20 rupees, 2700 rupees for 30 rupees, 3600 rupees for 40 rupees and 4500 rupees for 50 rupees. The user can invest as much money as he wants on one number and can play many numbers as he wants.',
  },
  {
    contentHead: 'Is it legal to play satta king game ?',
    isActive: true,
    contentPara:
      'The legality of the Satta king online is determined by the local government where the game is being played. If we talk about India, Betting is illegal and if caught playing you may have to pay heavy fine or serve a jail term. Still many people play sattaking in hiding from the authorities. Satta king is quite popular in India.',
  },
  {
    contentHead: 'How to play satta king online and why ?',
    isActive: true,
    contentPara:
      'Why should we play satta king online? If we talk about this, then the simple answer is that it is much easier to play Satta king onlne. If you want to play sattaking and stay safe from the police then playing satta king online could be a safe and better alternative. In the world of internet, catching online players is not an easy task. Yet we want to explicitly clarify here that according to the Indian laws betting is illegal and if caught betting you may have to pay a hefty fine. If you desire you may find many applications on the Google Play store, which can aid you to play sattaking game online. All you have do is to download the application and install it. Then you can play satta game at the comfort of your home.',
  },
  {
    contentHead: 'DISCLAIMER',
    isActive: true,
    contentPara:
      'This website is being run only through the preaching of entertainment. The website owner and we have nothing to do with any speculative company. Give money transactions on your responsibility. The website owner shall not be responsible for any fraud.',
  },
];

export const RecordCharts = [
  {
    isActive: true,
    chart: 'DISAWER CHART',
  },
  {
    isActive: true,
    chart: 'GALI CHART',
  },
  {
    isActive: true,
    chart: 'FARIDABAD CHART',
  },
  {
    isActive: true,
    chart: 'GAZIYABAD CHART',
  },
  {
    isActive: true,
    chart: 'SOUTH DELHI CHART',
  },
  {
    isActive: true,
    chart: 'PUNE CHART',
  },
  {
    isActive: true,
    chart: 'RANCHI CHART',
  },
  {
    isActive: true,
    chart: 'HINDUSTAN CHART',
  },
  {
    isActive: true,
    chart: 'KAVERI CHART',
  },
  {
    isActive: true,
    chart: 'OLD DELHI CHART',
  },
  {
    isActive: true,
    chart: 'KASHIPUR CHART',
  },
  {
    isActive: true,
    chart: 'DELHI CITY CHART',
  },
  {
    isActive: true,
    chart: 'PUNJAB CHART',
  },
];
