name: Cloudflare Pages Deployment

on:
  push:
    branches: ["main"]
    paths:
      - "apps/sattakingfaridabad/**"
      - "apps/sattakingfast/**"
      - "apps/sattakingresult/**"
      - ".github/workflows/cloudflarepages_deployment.yaml"
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #   TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      # - name: send telegram message on push
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: |
      #       ${{ github.actor }} created commit:
      #       Commit message: ${{ github.event.commits[0].message }}

      #       Repository: ${{ github.repository }}

      #       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      # - name: send telegram message on push
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELE_PLUTO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: |
      #       ${{ github.actor }} created commit:
      #       Commit message: ${{ github.event.commits[0].message }}

      #       Repository: ${{ github.repository }}

      #       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.11.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run pages-prod

      - name: sattakingfaridabad.pages.dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sattakingfaridabad # e.g. 'my-project'
          directory: apps/sattakingfaridabad/out # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: sattakingfast.pages.dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sattakingfast # e.g. 'my-project'
          directory: apps/sattakingfast/out # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: sattakingresult.pages.dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sattakingresult # e.g. 'my-project'
          directory: apps/sattakingresult/out # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
